// <auto-generated />
using Drones.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Drones.Migrations
{
    [DbContext(typeof(DronesContext))]
    partial class DronesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("DroneMedication", b =>
                {
                    b.Property<int>("DroneId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedicationsMedicationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DroneId", "MedicationsMedicationId");

                    b.HasIndex("MedicationsMedicationId");

                    b.ToTable("DroneMedication");
                });

            modelBuilder.Entity("Drones.Models.Drone", b =>
                {
                    b.Property<int>("DroneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BatteryCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Model")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeightLimit")
                        .HasColumnType("INTEGER");

                    b.HasKey("DroneId");

                    b.HasIndex("SN")
                        .IsUnique();

                    b.ToTable("Drones");
                });

            modelBuilder.Entity("Drones.Models.Medication", b =>
                {
                    b.Property<int>("MedicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("MedicationId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("DroneMedication", b =>
                {
                    b.HasOne("Drones.Models.Drone", null)
                        .WithMany()
                        .HasForeignKey("DroneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Drones.Models.Medication", null)
                        .WithMany()
                        .HasForeignKey("MedicationsMedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
